http:
  routers:
    traefik:
      entryPoints: 
        - secure
      rule: Host(`dashboard.{{ env "ROOT_DOMAIN" }}`)
      service: api@internal
      tls:
        certresolver: "le"
        domains:
          - main: {{ env "ROOT_DOMAIN" }}
            sans:
              - {{ $sans := env "ROOT_DOMAIN"}}"*.{{ $sans }}"

  middlewares:
    authelia:
      forwardAuth: 
        address: http://authelia:9091/api/verify?rd=https://logins.{{ env "ROOT_DOMAIN" }}
      trustForwardHeader: true
    guacamole:
      addPrefix:
        prefix: /guacamole