http:
  routers:
    traefik:
      entryPoints: 
        - secure
      rule: Host(`{{ env "DASHBOARD_DOMAIN" }}`)
      service: api@internal
      tls:
        certresolver: "le"
        domains:
          - main: {{ env "ROOT_DOMAIN" }}
            sans:
              - {{ $sans := env "ROOT_DOMAIN"}}"*.{{ $sans }}"

    # transmission:
    #   entryPoints:
    #     - secure
    #   service: transmission@file
    #   rule: Host(`{{ env "TRANSMISSION_DOMAIN" }}`)
    #   tls: {}

  # https://github.com/docker/for-linux/issues/264
  #   transmission:
  #     loadBalancer:
  #       servers:
  #         - url: http://host.docker.internal:9091


  middlewares:
    authelia:
      forwardAuth: 
        address: http://authelia:9091/api/verify?rd=https://{{ env "AUTHELIA_DOMAIN" }}
      trustForwardHeader: true