api: 
  dashboard: true

# log:
#   level: debug

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: secure
          scheme: https

  secure:
    address: ":443"

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true

providers:
    file:
      filename: ./dynamic.yml
    docker:
        exposedByDefault: false
        network: proxy
        endpoint: tcp://dockerproxy:2375

certificatesResolvers:
    le:
        acme:
            storage: /le/acme.json
            dnschallenge:
                provider: cloudflare