networks:
  meet.jitsi:

services:
    ###############################
    #           Jitsi             #
    ###############################
    web:
        image: jitsi/web
        container_name: jitsi-web
        volumes:
            - ${SERVICES_ROOT}/${JITSI_ROOT:-jitsi}/web:/config
            - ${SERVICES_ROOT}/${JITSI_ROOT:-jitsi}/transcripts:/usr/share/jitsi-meet/transcripts
        environment:
            - ENABLE_AUTH=1
            - ENABLE_GUESTS=0
            - ENABLE_LETSENCRYPT=0
            - ENABLE_HTTP_REDIRECT=0
            - ENABLE_TRANSCRIPTIONS=0
            - DISABLE_HTTPS=1
            - JICOFO_AUTH_USER=focus
            - PUBLIC_URL=${JITSI_DOMAIN}
            - XMPP_DOMAIN=meet.jitsi
            - XMPP_AUTH_DOMAIN=auth.meet.jitsi
            - XMPP_BOSH_URL_BASE=http://xmpp.meet.jitsi:5280
            - XMPP_GUEST_DOMAIN=guest.meet.jitsi
            - XMPP_MUC_DOMAIN=muc.meet.jitsi
            - XMPP_RECORDER_DOMAIN=recorder.meet.jitsi
            - ETHERPAD_URL_BASE=http://etherpad.meet.jitsi:9001
            - TZ
            - JIBRI_BREWERY_MUC=jigasibrewery
            - JIBRI_PENDING_TIMEOUT=90
            - JIBRI_XMPP_USER=jibri
            - JIBRI_XMPP_PASSWORD=${JIBRI_XMPP_PASSWORD:-XMPP password must be set for Jitsi}
            - JIBRI_RECORDER_USER=recorder
            - JIBRI_RECORDER_PASSWORD=${JIBRI_RECORDER_PASSWORD:-Recorder password must be set for Jitsi}
            - ENABLE_RECORDING=1

        networks:
            # traefik: change the following line to your external docker network
            proxy:
            meet.jitsi:
                aliases:
                    - meet.jitsi
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.jitsi.entrypoints=secure"
            - "traefik.http.routers.jitsi.rule=Host(`${JITSI_DOMAIN}`)"
            - "traefik.http.routers.jitsi.tls=true"
    # XMPP server
    prosody:
        image: jitsi/prosody
        container_name: jitsi-prosody
        expose:
            - '5222'
            - '5347'
            - '5280'
        volumes:
            - ${SERVICES_ROOT}/${JITSI_ROOT:-jitsi}/prosody:/config
        environment:
            - AUTH_TYPE=ldap
            - ENABLE_AUTH=1
            - ENABLE_GUESTS=0
            - GLOBAL_MODULES=statistics,alert
            - GLOBAL_CONFIG
            - LDAP_URL=ldap://openldap:389
            - LDAP_BASE=ou=people,${LDAP_LOGIN_BASE}
            - LDAP_BINDDN=cn=admin,${LDAP_LOGIN_BASE}
            - LDAP_BINDPW=${LDAP_ADMIN_PASSWORD}
            - LDAP_USE_TLS=0
            - LDAP_FILTER=(uid=%u)
            - LDAP_AUTH_METHOD=bind
            - LDAP_VERSION=3
            - XMPP_DOMAIN=meet.jitsi
            - XMPP_AUTH_DOMAIN=auth.meet.jitsi
            - XMPP_BOSH_URL_BASE=http://xmpp.meet.jitsi:5280
            - XMPP_GUEST_DOMAIN=guest.meet.jitsi
            - XMPP_MUC_DOMAIN=muc.meet.jitsi
            - XMPP_RECORDER_DOMAIN=recorder.meet.jitsi
            - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
            - XMPP_MODULES=info,alert
            - XMPP_MUC_MODULES=info,alert
            - XMPP_INTERNAL_MUC_MODULES=info,alert
            - JICOFO_COMPONENT_SECRET=${JICOFO_COMPONENT_SECRET:-Must enter a secret for Jicofo (Jitsi)}
            - JICOFO_AUTH_USER=focus
            - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD:-Must enter a passord for Jicofo admin (Jitsi)}
            - JVB_AUTH_USER=jvb
            - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD:-Must enter a passord for JVB auth (Jitsi)}
            - JIGASI_XMPP_USER=jigasi
            - JIGASI_XMPP_PASSWORD=${JICOFO_XMPP_PASSWORD:-Must enter a passord for Jigasi XMPP (Jitsi)}
            - JIBRI_XMPP_USER=jibri
            - JIBRI_XMPP_PASSWORD=${JIBRI_XMPP_PASSWORD:-XMPP password must be set for Jitsi}
            - JIBRI_RECORDER_USER=recorder
            - JIBRI_RECORDER_PASSWORD=${JIBRI_RECORDER_PASSWORD:-Recorder password must be set for Jitsi}
            - LOG_LEVEL
            - TZ
        networks:
            proxy:
            meet.jitsi:
                aliases:
                    - xmpp.meet.jitsi
    # Focus component
    jicofo:
        image: jitsi/jicofo
        container_name: jitsi-jicofo
        volumes:
            - ${SERVICES_ROOT}/${JITSI_ROOT:-jitsi}/jicofo:/config
        environment:
            - ENABLE_AUTH=1
            - XMPP_DOMAIN=meet.jitsi
            - XMPP_AUTH_DOMAIN=auth.meet.jitsi
            - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
            - XMPP_SERVER=xmpp.meet.jitsi
            - JICOFO_COMPONENT_SECRET=${JICOFO_COMPONENT_SECRET:-Must enter a secret for Jicofo (Jitsi)}
            - JICOFO_AUTH_USER=focus
            - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD:-Must enter a passord for Jicofo admin (Jitsi)}
            - JICOFO_RESERVATION_REST_BASE_URL=http://reservation.${ROOT_DOMAIN}
            - JVB_BREWERY_MUC=jvbbrewery
            - JIGASI_BREWERY_MUC=jigasibrewery
            - JIBRI_BREWERY_MUC=jigasibrewery
            - JIBRI_PENDING_TIMEOUT=90
            - TZ
        depends_on:
            - prosody
        networks:
            meet.jitsi:
    # Video bridge
    jvb:
        image: jitsi/jvb
        container_name: jitsi-jvb
        ports:
            - '10000:10000/udp'
            - '4443:4443'
        volumes:
            - ${SERVICES_ROOT}/${JITSI_ROOT:-jitsi}/jvb:/config
        environment:
            - DOCKER_HOST_ADDRESS=192.168.1.98
            - XMPP_AUTH_DOMAIN=auth.meet.jitsi
            - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
            - XMPP_SERVER=xmpp.meet.jitsi
            - JVB_AUTH_USER=jvb
            - JVB_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD:-Must enter a passord for Jicofo admin (Jitsi)}
            - JVB_BREWERY_MUC=jvbbrewery
            - JVB_PORT=10000
            - JVB_TCP_HARVESTER_DISABLED=true
            - JVB_TCP_PORT=4443
            - JVB_STUN_SERVERS=meet-jit-si-turnrelay.jitsi.net:443
            - JVB_ENABLE_APIS
            - TZ
        depends_on:
            - prosody
        networks:
            meet.jitsi: