[[servers]]
host = "openldap"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = false
bind_dn = "cn=admin,${LDAP_LOGIN_BASE}"
bind_password = '${LDAP_ADMIN_PASSWORD}'
search_filter = "(cn=%s)"
search_base_dns = ["${LDAP_LOGIN_BASE}"]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "memberOf"
email =  "email"
