[[servers]]
host = "openldap"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = false
bind_dn = "cn=readonly,${LDAP_LOGIN_BASE}"
bind_password = '${LDAP_READONLY_USER_PASSWOR}'
search_filter = "(uid=%s)"
search_base_dns = ["${LDAP_LOGIN_BASE}"]

[servers.attributes]
name = "displayName"
surname = "sn"
username = "uid"
member_of = "memberOf"
email =  "email"

[[servers.group_mappings]]
group_dn = "cn=administrator,ou=groups,${LDAP_LOGIN_BASE}"
org_role = "Admin"
grafana_admin = true # Available in Grafana v5.3 and above

[[servers.group_mappings]]
group_dn = "cn=everybody,ou=groups,${LDAP_LOGIN_BASE}"
org_role = "Viewer"
